CREATE TABLE SEG1(MATRÍCULA DOUBLE,NOME VARCHAR(10),FUNÇÃO VARCHAR(10),RG VARCHAR(10),CPF VARCHAR(10),ESCALA VARCHAR(10),CONTRATO VARCHAR(10),GASES_E_SEUS_RISCOS
MONITORAMENTO_DE_GASES_-_USO_DE_DETECTORES_DE_GASES VARCHAR(10),PIST_ÚNICO VARCHAR(10),ACESSO_AS_ÁREAS_OPERACIONAIS_DA_COQUERIA VARCHAR(10),NR_10_-_40_HORAS
ELETRICISTA VARCHAR(10),HABILITADO_EMPILHADEIRA VARCHAR(10),HABILITADO_MANIPULADOR_TELESCÓPIO VARCHAR(10),SINALIZAÇÃO_DE_EQUIPAMENTOS_DE_IÇAMENTO_E_AMARRAÇÃO_E_ESTROPAGEM_DE_CARGA VARCHAR(10),NR_12
SEGURANÇA_NA_OPERAÇÃO_DE_EQUIPAMENTOS_MOTRIZES VARCHAR(10),MONTAGEM_E_DESMONTAGEM_DE_ANDAIME VARCHAR(10),HABILITADO_OPERAÇÃO_DE_PTA VARCHAR(10),CORTE_COM_OXI-FLAME VARCHAR(10),SEGURANÇA_NA_OPERAÇÃO_DE_SOLDAGEM_E_OXI-CORTE VARCHAR(10),NR_23_+_20
_BÁSICO_EM_COMBATE_A_INCÊNDIO VARCHAR(10),NR_26_
GESTÃO_EM_PRODUTOS_QUÍMICOS VARCHAR(10),NR_33_
SUPERVISÃO_EM_ESPAÇOS_CONFINADOS VARCHAR(10),NR_33_
ATIVIDADES_EM_ESPAÇOS_CONFINADOS VARCHAR(10),NR_35
_TRABALHO_EM_ALTURA VARCHAR(10),PASTA_DO_EMPREGADO VARCHAR(10));
INSERT INTO SEG1 (MATRÍCULA,NOME,FUNÇÃO,RG,CPF,ESCALA,CONTRATO,GASES_E_SEUS_RISCOS
MONITORAMENTO_DE_GASES_-_USO_DE_DETECTORES_DE_GASES,PIST_ÚNICO,ACESSO_AS_ÁREAS_OPERACIONAIS_DA_COQUERIA,NR_10_-_40_HORAS
ELETRICISTA,HABILITADO_EMPILHADEIRA,HABILITADO_MANIPULADOR_TELESCÓPIO,SINALIZAÇÃO_DE_EQUIPAMENTOS_DE_IÇAMENTO_E_AMARRAÇÃO_E_ESTROPAGEM_DE_CARGA,NR_12
SEGURANÇA_NA_OPERAÇÃO_DE_EQUIPAMENTOS_MOTRIZES,MONTAGEM_E_DESMONTAGEM_DE_ANDAIME,HABILITADO_OPERAÇÃO_DE_PTA,CORTE_COM_OXI-FLAME,SEGURANÇA_NA_OPERAÇÃO_DE_SOLDAGEM_E_OXI-CORTE,NR_23_+_20
_BÁSICO_EM_COMBATE_A_INCÊNDIO,NR_26_
GESTÃO_EM_PRODUTOS_QUÍMICOS,NR_33_
SUPERVISÃO_EM_ESPAÇOS_CONFINADOS,NR_33_
ATIVIDADES_EM_ESPAÇOS_CONFINADOS,NR_35
_TRABALHO_EM_ALTURA,PASTA_DO_EMPREGADO) VALUES 
(133241,'ABEILTON DE SOUZA NASCIMENTO
','AUXILIAR DE OPERAÇÃO','2.248.221','058.885.997-43','X','2012','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024','04/15/2024',''),
(132804,'ADEMILSON LAURENTINO ROSA','ELETRICISTA','','','','2012','','','','','','','','','','','','','','','','','',''),
(133055,'ALAFE PILATTI DE SOUZA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132792,'ALAN AMARAL DE MATTOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132555,'ALAN ISLAN DA SILVA RODRIGUES','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132665,'ALEF MACHADO  ALVES','OPERADOR DE MANUTENÇAO REFRATARIO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(133113,'ALESSANDRA GAIANI LEITE','ASSISTENTE DE PLANEJAMENTO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132681,'ALEX SANDRE MOREIRA DE LEMOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133048,'ALEXANDRE BARBOZA GUALBERTO','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(131918,'ALEXSANDRO DA SILVA BENEDITO','LIDER DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132477,'ALISSON CORREA BAIA','PEDREIRO REFRATARISTA III','','','','2012','','','','','','','','','','','','','','','','','',''),
(133072,'ALTAIR INACIO DA SILVA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132606,'ALVARO ALVES MACENA','OPERADOR DE MANUTENÇAO REFRATARIO III','','','','2012','','','','','','','','','','','','','','','','','',''),
(132674,'ANA CLAUDIA SOARES DE OLIVEIRA','TECNICO DE SEGURANCA DO TRABALHO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132591,'ANDERSON DE OLIVEIRA RIBEIRO','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133056,'ANDERSON LUIS DA SILVA CESPEDES','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132693,'ANDERSON PINHEIRO DA CRUZ','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(121105,'ANDRE ABADIO DE LIMA','GESTOR DE CONTROLE E PRODUÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132512,'ANDREY BARRETO SOUSA','OPERADOR DE MANUTENÇAO REFRATARIO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(133104,'ANDREY RODRIGUES CARNEIRO','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132595,'ARAO CORREA DA SILVA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132588,'ARTHUR LEONEL CAVALCANTI MOURA','OPERADOR DE MANUTENCAO REFRATARIA I','','','','2012','','','','','','','','','','','','','','','','','',''),
(133105,'BISMARQ SILVA DA ROCHA','LIDER DE MANUTENCAO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132717,'BRENO CESAR DE AQUINO DUTRA','PEDREIRO REFRATARISTA IV','','','','2012','','','','','','','','','','','','','','','','','',''),
(132585,'BRUNO CEZAR QUEIROZ CHAFIM','LIDER DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132554,'BRUNO CHRISTIAN RIBEIRO DOS REIS','OPERADOR DE MANUTENÇAO REFRATARIO III','','','','2012','','','','','','','','','','','','','','','','','',''),
(132565,'BRUNO DE OLIVEIRA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132794,'BRUNO DE OLIVEIRA SANTOS','OPERADOR DE MANUTENCAO REFRATARIA','','','','2012','','','','','','','','','','','','','','','','','',''),
(133058,'CAIO HENRIQUE DOS REIS BARBOSA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132513,'CARLOS ALBERTO RAMOS DE SOUZA','OPERADOR DE MANUTENÇAO REFRATARIO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132576,'CARLOS ALBERTO TORRES VELOSO','ELETRICISTA','','','','2012','','','','','','','','','','','','','','','','','',''),
(132557,'CARLOS EDUARDO RODRIGUES PEREIRA','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(133059,'CARLOS HENRIQUE ALVES DOS SANTOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133067,'CLAUDINEI DE SOUZA','OPERADOR DE MANUTENCAO REFRATARIA','','','','2012','','','','','','','','','','','','','','','','','',''),
(132577,'CLAUDIO DE SOUZA LOPES','MONTADOR DE ANDAIMES','','','','2012','','','','','','','','','','','','','','','','','',''),
(132836,'CLAUDIO DOS SANTOS MIRANDA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132701,'CLEBSON EDUARDO COSTA ALMEIDA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132625,'CLEIDSON PEREIRA DOS ANJOS','OPERADOR MANUTENÇÃO REFRATARIA III','','','','2012','','','','','','','','','','','','','','','','','',''),
(132850,'CRISTIANO BASTOS MIRANDA','LIDER DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132597,'CRISTIANO FEIJO DE MORAES','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133078,'DANIEL MENDES RODRIGUES','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132702,'DAVI GELSON SANTOS DIAS SATIRO','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132837,'DEYVERSON DA SILVA GENOEL','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132669,'DEYVISON JOSE RIBEIRO MARINHO','OPERADOR DE MANUTENÇAO REFRATARIO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132682,'DIEGO BARCELOS DE FRANCA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132579,'DIEGO DA SILVA MACHADO','ELETRICISTA','','','','2012','','','','','','','','','','','','','','','','','',''),
(132675,'DIEGO SANTOS BENICIO','AUXILIAR DE PLANEJAMENTO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132685,'DOUGLAS RODRIGUES GONCALVES','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132996,'EDDIE SOARES AIRES','TECNICO DE SEGURANCA DO TRABALHO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132686,'EDILSON ALVES PEREIRA','MONTADOR DE ANDAIMES','','','','2012','','','','','','','','','','','','','','','','','',''),
(132598,'EDIMILSON EVARISTO DOS SANTOS','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133049,'EDISIO ALAN OLIVEIRA DA SILVA','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132599,'EDISON DE PAULA SOARES','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132855,'EDSON CARVALHO DA COSTA','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132589,'EDSON VANDO DE LORENA','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132838,'EDUARDO DOS SANTOS SILVA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133060,'EDUARDO HENRIQUE MOREIRA SANTANA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133061,'EDUARDO LUIZ PARAGUAI DA SILVA JUNIOR','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132499,'ELI CARLOS SILVA CABRAL','PEDREIRO REFRATARISTA II ','','','','2012','','','','','','','','','','','','','','','','','',''),
(132795,'ELIAS DE SOUZA GONZAGA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133244,'ESTEVAO SOUZA GOMES','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133245,'EVANDRO DOS SANTOS MACHADO
','AUXILIAR DE OPERAÇÃO
','','','','2012','','','','','','','','','','','','','','','','','',''),
(132600,'EZEQUIEL CALISTO DA COSTA NASCIMENTO','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133266,'FABIANA CRISTINA DOS ANJOS NOGUEIRA','TÉCNICO DE SEGURANÇA DO TRABALHO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133246,'FABIANO DA ROCHA MOREIRA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132703,'FABIO DANTAS FERREIRA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132708,'FABIO PADILHA CARDOSO','ELETRICISTA','','','','2012','','','','','','','','','','','','','','','','','',''),
(133096,'FARLEY PITTER DUARTE','ASSISTENTE DE LOGISTICA','','','','2012','','','','','','','','','','','','','','','','','',''),
(132856,'FERNANDO LOUREIRO RIBEIRO','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132601,'FLAVIO BARBOSA DOS SANTOS SILVA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132687,'FRANCISCO CARLOS DA SILVA SANTOS','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132559,'FRANCISCO DE ASSIS FERREIRA SOARES','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(133074,'FRANCISCO EDVALDO ROSENDO','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132839,'GABRIEL VIANA DA SILVA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132536,'GELSON MACHADO DE FREITAS','PEDREIRO REFRATARISTA IV','','','','2012','','','','','','','','','','','','','','','','','',''),
(132694,'GEOVANI FERREIRA CASTRO','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132422,'GUILHERME AUGUSTO OLIVEIRA VALADARES SILVA','MECANICO DE MANUTENÇAO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(133106,'GUILHERME MARINHO BARBOSA','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132688,'GUSTAVO AURELIO GUIMARAES PERES','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132840,'HALLISON GUIMARAES RESENDE','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132813,'HENRIQUE DA MOTA ROSA','LIDER DE PLANEJAMENTO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132552,'HERMES MARGALHO RODRIGUES','ENCARREGADO DE REFRATARIO I ','','','','2012','','','','','','','','','','','','','','','','','',''),
(132679,'HUGO GARCIA DOS SANTOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132689,'HUMBERTO LUIS LOREDO DA SILVA VIEGAS','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132568,'IEGO DE SOUZA HIGINO','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132560,'IVA SANTANA DOS SANTOS','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132586,'IVO DE JESUS BAGANHA','SUPERVISOR DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132518,'JADERSON NOGUEIRA TEIXEIRA','ENCARREGADO DE REFRATARIO I','','','','2012','','','','','','','','','','','','','','','','','',''),
(103459,'JAILSON DEODORO DUQUE','LIDER DE MANUTEÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132569,'JEFFERSON MARTINS DO NASCIMENTO','OPERADOR DE MANUTENCAO REFRATARIA','','','','2012','','','','','','','','','','','','','','','','','',''),
(132570,'JEFFERSON SALVADOR SILVA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132522,'JOAO PAULO PEREIRA DA SILVA','OFICIAL REFRATARISTA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132571,'JOAO PAULO SANTIAGO SENRA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132520,'JOAO VITOR INACIO SANTOS','PEDREIRO REFRATARISTA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132590,'JOAO VITOR PEREIRA DE SOUSA','OPERADOR DE MANUTENCAO REFRATARIA','','','','2012','','','','','','','','','','','','','','','','','',''),
(133107,'JOELSON QUARESMA FERREIRA','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(133247,'JORGE LUIZ DOS SANTOS MAIA JUNIOR','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133063,'JOSE ILSON PASSOS SILVA','MONTADOR DE ANDAIMES','','','','2012','','','','','','','','','','','','','','','','','',''),
(132851,'JOSE MARCOS DE OLIVEIRA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133045,'JOSE MARIO GONCALVES DOS SANTOS','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(131610,'JOSE ROBERTO MACHADO','OPERADOR DE MANUTENCAO REFRATARIA','','','','2012','','','','','','','','','','','','','','','','','',''),
(132550,'JOSE ROBERTO RIBEIRO','OPERADOR DE MANUTENÇAO REFRATARIO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132827,'JOSELITO DE BRITO BARBOSA','LIDER DE MANUTENCAO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(133248,'JOSIAS TEIXEIRA BARROSO','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132709,'JULIO CESAR PINHEIRO DOMINGOS','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132710,'KEITON MOREIRA','LIDER DE MANUTENCAO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132695,'LAUAN AUGUSTO SOUZA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132711,'LEONARDO PIOVESAN DA SILVA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132806,'LUAN EVERDAM SILVA SANTOS','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132572,'LUAN WENDERSON DA SILVA DIAS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132805,'LUCAS DE OLIVEIRA LUZ','ELETRICISTA','','','','2012','','','','','','','','','','','','','','','','','',''),
(132802,'LUCAS FRANCISCO SANTOS DA SILVA ROCHA','LIDER DE MANUTENÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133086,'LUCAS MATHEUS IDALINO SILVA','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(133046,'LUCAS SANTOS DE SOUZA','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132796,'LUIS FERNANDO DA SILVA JUNIOR','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132690,'LUIS GOMES','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132842,'LUIS HENRIQUE CONCEICAO DA SILVA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132704,'LUIZ HENRIQUE DIAS MORAES CARNEIRO','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133062,'MARCIO DOS SANTOS SANTANA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133085,'MARCIO PEREIRA MACIEL','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132803,'MARCO AURELIO DE FARIA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132797,'MARCOS LAUDELINO FLORES','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132808,'MARCOS PAULO ALVES SALES','MONTADOR DE ANDAIMES','','','','2012','','','','','','','','','','','','','','','','','',''),
(133083,'MARCOS SILVA E SILVA','OPERADOR DE MANUTENCAO REFRATARIA III','','','','2012','','','','','','','','','','','','','','','','','',''),
(132563,'MARCOS VINICIUS FERREIRA DE SOUSA','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132835,'MARCUS VINICIUS MESQUITA DA SILVA','AUXILIAR DE ALMOXARIFADO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132705,'MARCUS VINICIUS SILVA DOS SANTOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133044,'MATEUS MORAES DE ALMEIDA','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132843,'MATHEUS DE CAMPOS BICACO','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133249,'MATHEUS HENRIQUE GOMES DIAS','AUXILIAR DE OPERAÇÃO
','','','','2012','','','','','','','','','','','','','','','','','',''),
(132713,'MATHEUS ROCHA GOUVEA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132593,'MIKE STEPHAN DOS SANTOS','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132574,'MOISES DE SOUZA LIMA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132483,'NILSON COSTA DA SILVA','SUPERVISOR DE OBRAS','','','','2012','','','','','','','','','','','','','','','','','',''),
(133108,'OTONILDO DA SILVA PINHEIRO','OPERADOR DE MANUTENCAO REFRATARIA III','','','','2012','','','','','','','','','','','','','','','','','',''),
(132798,'PABLO LUIS DA SILVA COSTA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132691,'PABLO RANIEILLY AMARO PELAEZ','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132807,'PATRICK SILVA SANTOS','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133075,'PAULO ANTONIO FERREIRA DA SILVA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133051,'PAULO ROBERTO FRAGA DANIEL','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(133250,'PAULO ROBERTO GOULART JUNIOR','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132692,'PEDRO LUCAS COSTA DE OLIVEIRA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132852,'RAFAEL DA SILVA','MONTADOR DE ANDAIMES','','','','2012','','','','','','','','','','','','','','','','','',''),
(132697,'RAFAEL HENRIQUE DE BARROS BELMONTE','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132832,'RAFAEL SILVA PESSSOA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133124,'RAMON DIAS DOS SANTOS DA SILVA','LIDER DE MANUTENÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132582,'REFSON LIMA SOUZA','MONTADOR DE ANDAIMES','','','','2012','','','','','','','','','','','','','','','','','',''),
(133251,'RENAN CAYTANO DANTAS DE OLIVEIRA','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(130563,'RENAN KENNED AMORIM SILVA','PEDREIRO REFRATARISTA IV','','','','2012','','','','','','','','','','','','','','','','','',''),
(132706,'RENER DA SILVA MORAES','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132564,'RICARDO ALVES TEIXEIRA','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132680,'RICARDO DO NASCIMENTO MULLER','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132801,'RICARDO SANTANA LISBOA','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(131263,'RICHARD ACCACIO DA SILVA RIBEIRO','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132510,'RODRIGO CLEOFAS DE CARVALHO VENTURA','ENCARREGADO DE REFRATARIO IV','','','','2012','','','','','','','','','','','','','','','','','',''),
(132809,'RODRIGO DA SILVA SANTOS','MONTADOR DE ANDAIMES','','','','2012','','','','','','','','','','','','','','','','','',''),
(131890,'ROGERIO RABELO','AUXILIAR DE OPERACAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132551,'RONALDO SANCHES BAIA','OPERADOR DE MANUTENÇAO REFRATARIO II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132833,'RUAN DOS SANTOS ROCHA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132698,'SAMUEL REIS JUNIOR','MECANICO DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132799,'SANDERSON BARBOZA DE OLIVEIRA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132603,'SANDY VIDAL TOME DE ALMEIDA','ASSISTENTE ADMINISTRATIVO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132834,'SEBASTIAO VINICIUS DE OLIVEIRA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(130573,'SIDNEI MARIANO','SUPERVISOR DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(131922,'THIAGO ALVES NUNES','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132575,'THIAGO ALVES PEREIRA','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132857,'THIAGO LUIZ DE SOUZA PINTO','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132684,'VAGNER DUARTE DOS SANTOS DA SILVA','SOLDADOR','','','','2012','','','','','','','','','','','','','','','','','',''),
(132566,'VANDERSON FORTUNATO RAMOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132793,'VANDO INACIO DOS SANTOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133109,'VINICIUS KAUA QUARESMA AMORIM','OPERADOR DE MANUTENCAO REFRATARIA II','','','','2012','','','','','','','','','','','','','','','','','',''),
(132567,'VITOR BARBOZA DE CASTRO','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(132854,'VITOR HUGO DE ALVARENGA NASCIMENTO','MONTADOR DE ANDAIMES','','','','2012','','','','','','','','','','','','','','','','','',''),
(131556,'WELLINGTON DE OLIVEIRA ECCARD','OPERADOR DE MANUTENCAO REFRATARIA III','','','','2012','','','','','','','','','','','','','','','','','',''),
(133064,'WESLEY MOREIRA DA SILVA','LIDER DE MANUTENCAO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133242,'WESLLEY LOPES SANTOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','',''),
(133243,'WEVERTON LOPES SANTOS','AUXILIAR DE OPERAÇÃO','','','','2012','','','','','','','','','','','','','','','','','','');